"""Geo token sets and country-code names used for region classification."""

EU_COUNTRIES = set(
    [
        "germany",
        "netherlands",
        "spain",
        "portugal",
        "uk",
        "gb",
        "eng",
        "sct",
        "united kingdom",
        "england",
        "scotland",
        "wales",
        "northern ireland",
        "ireland",
        "sweden",
        "denmark",
        "finland",
        "austria",
        "switzerland",
        "france",
        "italy",
        "poland",
        "czech republic",
        "czechia",
        "belgium",
        "luxembourg",
        "norway",
        "estonia",
        "latvia",
        "lithuania",
        "romania",
        "bulgaria",
        "croatia",
        "hungary",
        "slovakia",
        "slovenia",
        "greece",
        "cyprus",
        "malta",
        "europe",
        "european union",
        "eu",
        "eea",
        "emea",
    ]
)

EU_CITIES = set(
    [
        "berlin",
        "munich",
        "hamburg",
        "frankfurt",
        "amsterdam",
        "rotterdam",
        "barcelona",
        "madrid",
        "lisbon",
        "porto",
        "london",
        "dublin",
        "stockholm",
        "copenhagen",
        "helsinki",
        "vienna",
        "zurich",
        "paris",
        "lyon",
        "milan",
        "rome",
        "warsaw",
        "prague",
        "brussels",
        "oslo",
        "tallinn",
        "riga",
        "vilnius",
        "bucharest",
        "budapest",
        "athens",
    ]
)

IL_LOCATIONS = set(
    [
        "israel",
        "tel aviv",
        "tel-aviv",
        "haifa",
        "jerusalem",
        "herzliya",
        "raanana",
        "ra'anana",
        "petah tikva",
        "petah-tikva",
        "beer sheva",
        "beer-sheva",
        "netanya",
        "rehovot",
        "rishon lezion",
        "rishon le-zion",
        "holon",
        "bnei brak",
        "modi'in",
        "modiin",
        "kfar saba",
        "rosh haayin",
        "yehud",
        "givat shmuel",
        "airport city",
        "lod",
        "ramla",
        "yokneam",
        "caesarea",
        "or yehuda",
        "kiryat gat",
        "ashkelon",
        "ashdod",
        "eilat",
    ]
)

CA_LOCATIONS = set(
    [
        "canada",
        "toronto",
        "vancouver",
        "montreal",
        "ottawa",
        "calgary",
        "edmonton",
        "winnipeg",
        "quebec",
        "british columbia",
        "ontario",
        "alberta",
    ]
)

AU_LOCATIONS = set(
    [
        "australia",
        "sydney",
        "melbourne",
        "brisbane",
        "perth",
        "adelaide",
        "canberra",
        "hobart",
        "darwin",
        "gold coast",
        "new south wales",
        "victoria",
        "queensland",
    ]
)

US_LOCATIONS = set(
    [
        "united states",
        "usa",
        "us",
        "u.s.",
        "u.s.a.",
        "new york",
        "san francisco",
        "los angeles",
        "seattle",
        "austin",
        "chicago",
        "boston",
        "denver",
        "miami",
        "atlanta",
        "dallas",
        "houston",
        "phoenix",
        "portland",
        "san diego",
        "san jose",
        "california",
        "texas",
        "washington",
        "massachusetts",
        "colorado",
        "florida",
        "georgia",
        "illinois",
        "pennsylvania",
        "virginia",
        "north carolina",
        "oregon",
        "arizona",
        "new jersey",
        "minnesota",
        "tennessee",
        "ohio",
        "michigan",
        "maryland",
        "connecticut",
        "utah",
    ]
)

_SHORT_LOCATION_TOKENS = set(["eu", "uk", "gb", "eng", "sct", "us", "u.s.", "u.s.a."])

COUNTRY_NAMES = {
    "AR": "Argentina",
    "AT": "Austria",
    "AU": "Australia",
    "BE": "Belgium",
    "BR": "Brazil",
    "CA": "Canada",
    "CH": "Switzerland",
    "CL": "Chile",
    "CO": "Colombia",
    "DE": "Germany",
    "DK": "Denmark",
    "ES": "Spain",
    "FI": "Finland",
    "FR": "France",
    "GB": "United Kingdom",
    "IE": "Ireland",
    "IL": "Israel",
    "IN": "India",
    "IT": "Italy",
    "MX": "Mexico",
    "NL": "Netherlands",
    "NZ": "New Zealand",
    "PL": "Poland",
    "PT": "Portugal",
    "SE": "Sweden",
    "US": "United States",
}
